name: "Frogbot Security Scan"
on: 
  push: # Triggers scan-repo flow for every push to the specified branches
    branches:
      - main

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  frogbot-scan:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # The repository scanning will be triggered periodically on the following branches.
        branch: ["main"]
    steps: 
    #   - name: Setup JFrog CLI OIDC
    #     uses: jfrog/setup-jfrog-cli@v4
    #     env:
    #        JF_URL: https://chida1.jfrog.io
    #     with:
    #        oidc-provider-name: github 
    #        oidc-audience: jfrog-github

       - name: frogbot
         uses: jfrog/frogbot@v2
         env:
          JF_URL: https://chida1.jfrog.io
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_GIT_BASE_BRANCH: ${{ matrix.branch }}
       